### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by AlexMAS** [zgmnkv/zwave4j#48]
Hello!

I would like to know project status. :) As I see the latest commit was a long time ago in 2016. And the latest release was in 2014. Could you say the reason or offer some alternative solutions for Java? I'm not so familiar with Z-Wave and currently I'm trying to find solution to work with Z-Wave devices.

Thank you.

**Comment by mcicolella** [comment]
@AlexMAS I'm afraid this project is abandoned.
I'm looking for a Java alternative too.

**Comment by zgmnkv** [comment]
Hi,
Unfortunately I don't have an ability to maintain this project currently.
The reason is that I don't use z-wave in my everyday life and I don't have many devices: only usb stick and dimmer. So I don't have a strong motivation to continue development of this library, and I can't fully test changes and new releases.
You are free to fork this lib and update to latest version of openzwave.
I have seen some other Java libs for z-wave including native Java libs but I'm not aware of how good they are.
Just first results from google:
https://github.com/whizzosoftware/WZWave
https://github.com/oberasoftware/zwave
https://github.com/NetHome/ZWave

**Comment by AlexMAS** [comment]
Thank you for your reply!
